import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    async function timeWorldApi() {
        const res = await fetch("https://worldtimeapi.org/api/timezone/Asia/Tokyo", { next: { tags: ["layout"] } })
        return res.json()
    }

    const resWorldTime = await timeWorldApi()

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <p>こちらは通常のlayoutタグのついたfetchです</p>
          <p>{ resWorldTime.datetime }</p>
        </header>
        {children}
      </body>
    </html>
  );
}
